
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

/*!40000 ALTER TABLE `modx_menus` DISABLE KEYS */;
REPLACE INTO `modx_menus` VALUES ('about','usernav','help','','<i class=\"icon-question-circle icon icon-large\"></i>',7,'','','help','core');
REPLACE INTO `modx_menus` VALUES ('acls','admin','security/permission','acls_desc','',5,'','','access_permissions','core');
REPLACE INTO `modx_menus` VALUES ('admin','usernav','','','<i class=\"icon-gear icon icon-large\"></i>',6,'','','settings','core');
REPLACE INTO `modx_menus` VALUES ('bespoke_manager','admin','security/forms','bespoke_manager_desc','',1,'','','customize_forms','core');
REPLACE INTO `modx_menus` VALUES ('clientconfig','components','home','clientconfig.desc','<i class=\"icon icon-wrench\"></i>',0,'','','','clientconfig');
REPLACE INTO `modx_menus` VALUES ('components','topnav','','','',2,'','','components','core');
REPLACE INTO `modx_menus` VALUES ('content_types','site','system/contenttype','content_types_desc','',8,'','','content_types','core');
REPLACE INTO `modx_menus` VALUES ('contexts','admin','context','contexts_desc','',3,'','','view_context','core');
REPLACE INTO `modx_menus` VALUES ('dashboards','admin','system/dashboards','dashboards_desc','',2,'','','dashboards','core');
REPLACE INTO `modx_menus` VALUES ('edit_menu','admin','system/action','edit_menu_desc','',4,'','','actions','core');
REPLACE INTO `modx_menus` VALUES ('eventlog_viewer','reports','system/event','eventlog_viewer_desc','',2,'','','view_eventlog','core');
REPLACE INTO `modx_menus` VALUES ('file_browser','media','media/browser','file_browser_desc','',0,'','','file_manager','core');
REPLACE INTO `modx_menus` VALUES ('flush_access','manage','','flush_access_desc','',3,'','MODx.msg.confirm({\n    title: _(\'flush_access\')\n    ,text: _(\'flush_access_confirm\')\n    ,url: MODx.config.connector_url\n    ,params: {\n        action: \'security/access/flush\'\n    }\n    ,listeners: {\n        \'success\': {fn:function() { location.href = \'./\'; },scope:this},\n        \'failure\': {fn:function(response) { Ext.MessageBox.alert(\'failure\', response.responseText); },scope:this},\n    }\n});','access_permissions','core');
REPLACE INTO `modx_menus` VALUES ('flush_sessions','manage','','flush_sessions_desc','',4,'','MODx.msg.confirm({\n    title: _(\'flush_sessions\')\n    ,text: _(\'flush_sessions_confirm\')\n    ,url: MODx.config.connector_url\n    ,params: {\n        action: \'security/flush\'\n    }\n    ,listeners: {\n        \'success\': {fn:function() { location.href = \'./\'; },scope:this}\n    }\n});','flush_sessions','core');
REPLACE INTO `modx_menus` VALUES ('formit','components','home','formit.desc','',0,'','','formit','formit');
REPLACE INTO `modx_menus` VALUES ('import_resources','site','system/import','import_resources_desc','',6,'','','import_static','core');
REPLACE INTO `modx_menus` VALUES ('import_site','site','system/import/html','import_site_desc','',5,'','','import_static','core');
REPLACE INTO `modx_menus` VALUES ('installer','components','workspaces','installer_desc','',0,'','','packages','core');
REPLACE INTO `modx_menus` VALUES ('lexicon_management','admin','workspaces/lexicon','lexicon_management_desc','',7,'','','lexicons','core');
REPLACE INTO `modx_menus` VALUES ('logout','user','security/logout','logout_desc','',2,'','MODx.logout(); return false;','logout','core');
REPLACE INTO `modx_menus` VALUES ('manage','topnav','','','',3,'','','menu_tools','core');
REPLACE INTO `modx_menus` VALUES ('media','topnav','','media_desc','',1,'','','file_manager','core');
REPLACE INTO `modx_menus` VALUES ('messages','user','security/message','messages_desc','',1,'','','messages','core');
REPLACE INTO `modx_menus` VALUES ('MIGX','components','index','','',1,'&configs=migxconfigs||packagemanager','','','migx');
REPLACE INTO `modx_menus` VALUES ('minishop2','components','mgr/orders','ms2_menu_desc','<i class=\"icon-shopping-cart icon icon-large\"></i>',0,'','','','minishop2');
REPLACE INTO `modx_menus` VALUES ('ms2_orders','minishop2','mgr/orders','ms2_orders_desc','',0,'','','','minishop2');
REPLACE INTO `modx_menus` VALUES ('ms2_settings','minishop2','mgr/settings','ms2_settings_desc','',1,'','','','minishop2');
REPLACE INTO `modx_menus` VALUES ('ms2_system_settings','minishop2','system/settings','ms2_system_settings_desc','',2,'&ns=minishop2','','settings','core');
REPLACE INTO `modx_menus` VALUES ('namespaces','admin','workspaces/namespace','namespaces_desc','',8,'','','namespaces','core');
REPLACE INTO `modx_menus` VALUES ('new_resource','site','resource/create','new_resource_desc','',0,'','','new_document','core');
REPLACE INTO `modx_menus` VALUES ('preview','site','','preview_desc','',4,'','MODx.preview(); return false;','','core');
REPLACE INTO `modx_menus` VALUES ('profile','user','security/profile','profile_desc','',0,'','','change_profile','core');
REPLACE INTO `modx_menus` VALUES ('propertysets','admin','element/propertyset','propertysets_desc','',6,'','','property_sets','core');
REPLACE INTO `modx_menus` VALUES ('refreshuris','refresh_site','','refreshuris_desc','',0,'','MODx.refreshURIs(); return false;','empty_cache','core');
REPLACE INTO `modx_menus` VALUES ('refresh_site','manage','','refresh_site_desc','',1,'','MODx.clearCache(); return false;','empty_cache','core');
REPLACE INTO `modx_menus` VALUES ('remove_locks','manage','','remove_locks_desc','',2,'','MODx.removeLocks();return false;','remove_locks','core');
REPLACE INTO `modx_menus` VALUES ('reports','manage','','reports_desc','',5,'','','menu_reports','core');
REPLACE INTO `modx_menus` VALUES ('resource_groups','site','security/resourcegroup','resource_groups_desc','',7,'','','access_permissions','core');
REPLACE INTO `modx_menus` VALUES ('site','topnav','','','',0,'','','menu_site','core');
REPLACE INTO `modx_menus` VALUES ('site_schedule','reports','resource/site_schedule','site_schedule_desc','',0,'','','view_document','core');
REPLACE INTO `modx_menus` VALUES ('sources','media','source','sources_desc','',1,'','','sources','core');
REPLACE INTO `modx_menus` VALUES ('system_settings','admin','system/settings','system_settings_desc','',0,'','','settings','core');
REPLACE INTO `modx_menus` VALUES ('topnav','','','topnav_desc','',0,'','','','core');
REPLACE INTO `modx_menus` VALUES ('user','usernav','','','<span id=\"user-avatar\">{$userImage}</span> <span id=\"user-username\">{$username}</span>',5,'','','menu_user','core');
REPLACE INTO `modx_menus` VALUES ('usernav','','','usernav_desc','',0,'','','','core');
REPLACE INTO `modx_menus` VALUES ('users','manage','security/user','user_management_desc','',0,'','','view_user','core');
REPLACE INTO `modx_menus` VALUES ('view_logging','reports','system/logs','view_logging_desc','',1,'','','logs','core');
REPLACE INTO `modx_menus` VALUES ('view_sysinfo','reports','system/info','view_sysinfo_desc','',3,'','','view_sysinfo','core');
/*!40000 ALTER TABLE `modx_menus` ENABLE KEYS */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

