
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

/*!40000 ALTER TABLE `modx_system_settings` DISABLE KEYS */;
REPLACE INTO `modx_system_settings` VALUES ('access_category_enabled','1','combo-boolean','core','authentication',NULL);
REPLACE INTO `modx_system_settings` VALUES ('access_context_enabled','1','combo-boolean','core','authentication',NULL);
REPLACE INTO `modx_system_settings` VALUES ('access_resource_group_enabled','1','combo-boolean','core','authentication',NULL);
REPLACE INTO `modx_system_settings` VALUES ('allow_forward_across_contexts','','combo-boolean','core','system',NULL);
REPLACE INTO `modx_system_settings` VALUES ('allow_manager_login_forgot_password','1','combo-boolean','core','authentication',NULL);
REPLACE INTO `modx_system_settings` VALUES ('allow_multiple_emails','1','combo-boolean','core','authentication',NULL);
REPLACE INTO `modx_system_settings` VALUES ('allow_tags_in_post','','combo-boolean','core','system',NULL);
REPLACE INTO `modx_system_settings` VALUES ('allow_tv_eval','1','combo-boolean','core','system',NULL);
REPLACE INTO `modx_system_settings` VALUES ('anonymous_sessions','1','combo-boolean','core','session',NULL);
REPLACE INTO `modx_system_settings` VALUES ('archive_with','','combo-boolean','core','system',NULL);
REPLACE INTO `modx_system_settings` VALUES ('automatic_alias','1','combo-boolean','core','furls',NULL);
REPLACE INTO `modx_system_settings` VALUES ('automatic_template_assignment','parent','textfield','core','site',NULL);
REPLACE INTO `modx_system_settings` VALUES ('auto_check_pkg_updates','1','combo-boolean','core','system',NULL);
REPLACE INTO `modx_system_settings` VALUES ('auto_check_pkg_updates_cache_expire','15','textfield','core','system',NULL);
REPLACE INTO `modx_system_settings` VALUES ('auto_isfolder','1','combo-boolean','core','site',NULL);
REPLACE INTO `modx_system_settings` VALUES ('auto_menuindex','1','combo-boolean','core','site',NULL);
REPLACE INTO `modx_system_settings` VALUES ('base_help_url','//docs.modx.com/help/','textfield','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('blocked_minutes','60','textfield','core','authentication',NULL);
REPLACE INTO `modx_system_settings` VALUES ('cache_action_map','1','combo-boolean','core','caching',NULL);
REPLACE INTO `modx_system_settings` VALUES ('cache_alias_map','1','combo-boolean','core','caching',NULL);
REPLACE INTO `modx_system_settings` VALUES ('cache_context_settings','1','combo-boolean','core','caching',NULL);
REPLACE INTO `modx_system_settings` VALUES ('cache_db','0','combo-boolean','core','caching',NULL);
REPLACE INTO `modx_system_settings` VALUES ('cache_db_expires','0','textfield','core','caching',NULL);
REPLACE INTO `modx_system_settings` VALUES ('cache_db_session','0','combo-boolean','core','caching',NULL);
REPLACE INTO `modx_system_settings` VALUES ('cache_db_session_lifetime','','textfield','core','caching',NULL);
REPLACE INTO `modx_system_settings` VALUES ('cache_default','1','combo-boolean','core','caching',NULL);
REPLACE INTO `modx_system_settings` VALUES ('cache_expires','0','textfield','core','caching',NULL);
REPLACE INTO `modx_system_settings` VALUES ('cache_format','0','textfield','core','caching',NULL);
REPLACE INTO `modx_system_settings` VALUES ('cache_handler','xPDOFileCache','textfield','core','caching',NULL);
REPLACE INTO `modx_system_settings` VALUES ('cache_lang_js','1','combo-boolean','core','caching',NULL);
REPLACE INTO `modx_system_settings` VALUES ('cache_lexicon_topics','1','combo-boolean','core','caching',NULL);
REPLACE INTO `modx_system_settings` VALUES ('cache_noncore_lexicon_topics','1','combo-boolean','core','caching',NULL);
REPLACE INTO `modx_system_settings` VALUES ('cache_resource','1','combo-boolean','core','caching',NULL);
REPLACE INTO `modx_system_settings` VALUES ('cache_resource_clear_partial','0','combo-boolean','core','caching',NULL);
REPLACE INTO `modx_system_settings` VALUES ('cache_resource_expires','0','textfield','core','caching',NULL);
REPLACE INTO `modx_system_settings` VALUES ('cache_scripts','1','combo-boolean','core','caching',NULL);
REPLACE INTO `modx_system_settings` VALUES ('clear_cache_refresh_trees','0','combo-boolean','core','caching',NULL);
REPLACE INTO `modx_system_settings` VALUES ('clientconfig.admin_groups','Administrator','textfield','clientconfig','Default',NULL);
REPLACE INTO `modx_system_settings` VALUES ('clientconfig.clear_cache','1','combo-boolean','clientconfig','Default',NULL);
REPLACE INTO `modx_system_settings` VALUES ('clientconfig.context_aware','1','combo-boolean','clientconfig','Default','2024-11-15 17:52:23');
REPLACE INTO `modx_system_settings` VALUES ('clientconfig.google_fonts_api_key','','textfield','clientconfig','Default',NULL);
REPLACE INTO `modx_system_settings` VALUES ('clientconfig.vertical_tabs','','combo-boolean','clientconfig','Default',NULL);
REPLACE INTO `modx_system_settings` VALUES ('codemirror.enable','1','combo-boolean','codemirror','Editor',NULL);
REPLACE INTO `modx_system_settings` VALUES ('compress_css','1','combo-boolean','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('compress_js','1','combo-boolean','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('compress_js_max_files','10','textfield','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('confirm_navigation','1','combo-boolean','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('container_suffix','/','textfield','core','furls',NULL);
REPLACE INTO `modx_system_settings` VALUES ('context_tree_sort','1','combo-boolean','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('context_tree_sortby','rank','textfield','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('context_tree_sortdir','ASC','textfield','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('cultureKey','ru','modx-combo-language','core','language','2024-11-15 16:33:05');
REPLACE INTO `modx_system_settings` VALUES ('date_timezone','','textfield','core','system',NULL);
REPLACE INTO `modx_system_settings` VALUES ('debug','','textfield','core','system',NULL);
REPLACE INTO `modx_system_settings` VALUES ('default_content_type','1','modx-combo-content-type','core','site',NULL);
REPLACE INTO `modx_system_settings` VALUES ('default_context','web','modx-combo-context','core','site',NULL);
REPLACE INTO `modx_system_settings` VALUES ('default_duplicate_publish_option','preserve','textfield','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('default_media_source','1','modx-combo-source','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('default_media_source_type','sources.modFileMediaSource','modx-combo-source-type','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('default_per_page','20','textfield','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('default_template','1','modx-combo-template','core','site',NULL);
REPLACE INTO `modx_system_settings` VALUES ('default_username','(anonymous)','textfield','core','session',NULL);
REPLACE INTO `modx_system_settings` VALUES ('editor_css_path','','textfield','core','editor',NULL);
REPLACE INTO `modx_system_settings` VALUES ('editor_css_selectors','','textfield','core','editor',NULL);
REPLACE INTO `modx_system_settings` VALUES ('emailsender','noreply@modxmain.com','textfield','core','authentication','2024-11-15 19:44:09');
REPLACE INTO `modx_system_settings` VALUES ('emailsubject','Your login details','textfield','core','authentication',NULL);
REPLACE INTO `modx_system_settings` VALUES ('enable_dragdrop','1','combo-boolean','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('enable_gravatar','1','combo-boolean','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('error_log_filename','error.log','textfield','core','system',NULL);
REPLACE INTO `modx_system_settings` VALUES ('error_log_filepath','','textfield','core','system',NULL);
REPLACE INTO `modx_system_settings` VALUES ('error_page','1','textfield','core','site',NULL);
REPLACE INTO `modx_system_settings` VALUES ('extension_packages','[{\"minishop2\":{\"path\":\"[[++core_path]]components/minishop2/model/\"}}]','textfield','core','system',NULL);
REPLACE INTO `modx_system_settings` VALUES ('failed_login_attempts','5','textfield','core','authentication',NULL);
REPLACE INTO `modx_system_settings` VALUES ('feed_modx_news','https://feeds.feedburner.com/modx-announce','textfield','core','system',NULL);
REPLACE INTO `modx_system_settings` VALUES ('feed_modx_news_enabled','1','combo-boolean','core','system',NULL);
REPLACE INTO `modx_system_settings` VALUES ('feed_modx_security','https://forums.modx.com/board.xml?board=294','textfield','core','system',NULL);
REPLACE INTO `modx_system_settings` VALUES ('feed_modx_security_enabled','1','combo-boolean','core','system',NULL);
REPLACE INTO `modx_system_settings` VALUES ('fe_editor_lang','en','modx-combo-language','core','language',NULL);
REPLACE INTO `modx_system_settings` VALUES ('filemanager_path','','textfield','core','file',NULL);
REPLACE INTO `modx_system_settings` VALUES ('filemanager_path_relative','1','combo-boolean','core','file',NULL);
REPLACE INTO `modx_system_settings` VALUES ('filemanager_url','','textfield','core','file',NULL);
REPLACE INTO `modx_system_settings` VALUES ('filemanager_url_relative','1','combo-boolean','core','file',NULL);
REPLACE INTO `modx_system_settings` VALUES ('forgot_login_email','<p>Hello [[+username]],</p>\n<p>A request for a password reset has been issued for your MODX user. If you sent this, you may follow this link and use this password to login. If you did not send this request, please ignore this email.</p>\n\n<p>\n    <strong>Activation Link:</strong> [[+url_scheme]][[+http_host]][[+manager_url]]?modahsh=[[+hash]]<br />\n    <strong>Username:</strong> [[+username]]<br />\n    <strong>Password:</strong> [[+password]]<br />\n</p>\n\n<p>After you log into the MODX Manager, you can change your password again, if you wish.</p>\n\n<p>Regards,<br />Site Administrator</p>','textarea','core','authentication',NULL);
REPLACE INTO `modx_system_settings` VALUES ('formit.attachment.mediasource','1','modx-combo-source','formit','formit',NULL);
REPLACE INTO `modx_system_settings` VALUES ('formit.attachment.path','','textfield','formit','formit',NULL);
REPLACE INTO `modx_system_settings` VALUES ('formit.cleanform.days','30','textfield','formit','formit',NULL);
REPLACE INTO `modx_system_settings` VALUES ('formit.exclude_contexts','mgr','textfield','formit','formit',NULL);
REPLACE INTO `modx_system_settings` VALUES ('formit.form_encryptkey','modx67374d3db86004.79451653','textfield','formit','formit','2024-11-15 17:46:01');
REPLACE INTO `modx_system_settings` VALUES ('formit.max_chars_textfield','125','textfield','formit','formit',NULL);
REPLACE INTO `modx_system_settings` VALUES ('formit.recaptcha_private_key','','textfield','formit','formit_recaptcha',NULL);
REPLACE INTO `modx_system_settings` VALUES ('formit.recaptcha_public_key','','textfield','formit','formit_recaptcha',NULL);
REPLACE INTO `modx_system_settings` VALUES ('formit.recaptcha_use_ssl','0','combo-boolean','formit','formit_recaptcha',NULL);
REPLACE INTO `modx_system_settings` VALUES ('form_customization_use_all_groups','','combo-boolean','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('forward_merge_excludes','type,published,class_key','textfield','core','system',NULL);
REPLACE INTO `modx_system_settings` VALUES ('friendly_alias_lowercase_only','1','combo-boolean','core','furls',NULL);
REPLACE INTO `modx_system_settings` VALUES ('friendly_alias_max_length','0','textfield','core','furls',NULL);
REPLACE INTO `modx_system_settings` VALUES ('friendly_alias_realtime','0','combo-boolean','core','furls',NULL);
REPLACE INTO `modx_system_settings` VALUES ('friendly_alias_restrict_chars','pattern','textfield','core','furls',NULL);
REPLACE INTO `modx_system_settings` VALUES ('friendly_alias_restrict_chars_pattern','/[\\0\\x0B\\t\\n\\r\\f\\a&=+%#<>\"~:`@\\?\\[\\]\\{\\}\\|\\^\'\\\\]/','textfield','core','furls',NULL);
REPLACE INTO `modx_system_settings` VALUES ('friendly_alias_strip_element_tags','1','combo-boolean','core','furls',NULL);
REPLACE INTO `modx_system_settings` VALUES ('friendly_alias_translit','russian','textfield','core','furls','2024-11-15 19:41:40');
REPLACE INTO `modx_system_settings` VALUES ('friendly_alias_translit_class','modx.translit.modTransliterate','textfield','core','furls','2024-11-15 17:52:09');
REPLACE INTO `modx_system_settings` VALUES ('friendly_alias_translit_class_path','{core_path}components/translit/model/','textfield','core','furls','2024-11-15 17:52:09');
REPLACE INTO `modx_system_settings` VALUES ('friendly_alias_trim_chars','/.-_','textfield','core','furls',NULL);
REPLACE INTO `modx_system_settings` VALUES ('friendly_alias_word_delimiter','-','textfield','core','furls',NULL);
REPLACE INTO `modx_system_settings` VALUES ('friendly_alias_word_delimiters','-_','textfield','core','furls',NULL);
REPLACE INTO `modx_system_settings` VALUES ('friendly_urls','1','combo-boolean','core','furls','2024-11-15 19:41:47');
REPLACE INTO `modx_system_settings` VALUES ('friendly_urls_strict','0','combo-boolean','core','furls',NULL);
REPLACE INTO `modx_system_settings` VALUES ('global_duplicate_uri_check','0','combo-boolean','core','furls',NULL);
REPLACE INTO `modx_system_settings` VALUES ('hidemenu_default','0','combo-boolean','core','site',NULL);
REPLACE INTO `modx_system_settings` VALUES ('inline_help','1','combo-boolean','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('link_tag_scheme','-1','textfield','core','site',NULL);
REPLACE INTO `modx_system_settings` VALUES ('locale','','textfield','core','language',NULL);
REPLACE INTO `modx_system_settings` VALUES ('lock_ttl','360','textfield','core','system',NULL);
REPLACE INTO `modx_system_settings` VALUES ('log_deprecated','1','combo-boolean','core','system',NULL);
REPLACE INTO `modx_system_settings` VALUES ('log_level','1','textfield','core','system',NULL);
REPLACE INTO `modx_system_settings` VALUES ('log_snippet_not_found','1','combo-boolean','core','site',NULL);
REPLACE INTO `modx_system_settings` VALUES ('log_target','FILE','textfield','core','system',NULL);
REPLACE INTO `modx_system_settings` VALUES ('mail_charset','UTF-8','modx-combo-charset','core','mail',NULL);
REPLACE INTO `modx_system_settings` VALUES ('mail_encoding','8bit','textfield','core','mail',NULL);
REPLACE INTO `modx_system_settings` VALUES ('mail_smtp_auth','','combo-boolean','core','mail',NULL);
REPLACE INTO `modx_system_settings` VALUES ('mail_smtp_autotls','1','combo-boolean','core','mail',NULL);
REPLACE INTO `modx_system_settings` VALUES ('mail_smtp_helo','','textfield','core','mail',NULL);
REPLACE INTO `modx_system_settings` VALUES ('mail_smtp_hosts','localhost','textfield','core','mail',NULL);
REPLACE INTO `modx_system_settings` VALUES ('mail_smtp_keepalive','','combo-boolean','core','mail',NULL);
REPLACE INTO `modx_system_settings` VALUES ('mail_smtp_pass','','text-password','core','mail',NULL);
REPLACE INTO `modx_system_settings` VALUES ('mail_smtp_port','587','textfield','core','mail',NULL);
REPLACE INTO `modx_system_settings` VALUES ('mail_smtp_prefix','','textfield','core','mail',NULL);
REPLACE INTO `modx_system_settings` VALUES ('mail_smtp_single_to','','combo-boolean','core','mail',NULL);
REPLACE INTO `modx_system_settings` VALUES ('mail_smtp_timeout','10','textfield','core','mail',NULL);
REPLACE INTO `modx_system_settings` VALUES ('mail_smtp_user','','textfield','core','mail',NULL);
REPLACE INTO `modx_system_settings` VALUES ('mail_use_smtp','','combo-boolean','core','mail',NULL);
REPLACE INTO `modx_system_settings` VALUES ('main_nav_parent','topnav','textfield','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('manager_date_format','Y-m-d','textfield','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('manager_direction','ltr','textfield','core','language',NULL);
REPLACE INTO `modx_system_settings` VALUES ('manager_favicon_url','','textfield','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('manager_js_cache_file_locking','1','combo-boolean','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('manager_js_cache_max_age','3600','textfield','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('manager_js_document_root','','textfield','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('manager_js_zlib_output_compression','0','combo-boolean','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('manager_language','ru','modx-combo-language','core','language','2024-11-15 16:33:05');
REPLACE INTO `modx_system_settings` VALUES ('manager_lang_attribute','ru','textfield','core','language','2024-11-15 16:33:05');
REPLACE INTO `modx_system_settings` VALUES ('manager_login_url_alternate','','textfield','core','authentication',NULL);
REPLACE INTO `modx_system_settings` VALUES ('manager_theme','default','modx-combo-manager-theme','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('manager_time_format','H:i','textfield','core','manager','2024-11-15 19:50:13');
REPLACE INTO `modx_system_settings` VALUES ('manager_use_fullname','0','combo-boolean','core','manager','2024-11-15 19:50:42');
REPLACE INTO `modx_system_settings` VALUES ('manager_week_start','1','textfield','core','manager','2024-11-15 19:50:46');
REPLACE INTO `modx_system_settings` VALUES ('mgr_source_icon','icon-folder-open-o','textfield','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('mgr_tree_icon_context','tree-context','textfield','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('mgr_tree_icon_mscategory','icon icon-barcode','textarea','minishop2','ms2_category',NULL);
REPLACE INTO `modx_system_settings` VALUES ('mgr_tree_icon_msproduct','icon icon-tag','textarea','minishop2','ms2_product',NULL);
REPLACE INTO `modx_system_settings` VALUES ('modx_browser_default_sort','name','textfield','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('modx_browser_default_viewmode','grid','textfield','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('modx_browser_tree_hide_files','1','combo-boolean','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('modx_browser_tree_hide_tooltips','1','combo-boolean','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('modx_charset','UTF-8','modx-combo-charset','core','language',NULL);
REPLACE INTO `modx_system_settings` VALUES ('ms2_add_icon_category','icon icon-folder-open','textfield','minishop2','ms2_category',NULL);
REPLACE INTO `modx_system_settings` VALUES ('ms2_add_icon_product','icon icon-tag','textfield','minishop2','ms2_category',NULL);
REPLACE INTO `modx_system_settings` VALUES ('ms2_cart_context','','combo-boolean','minishop2','ms2_cart',NULL);
REPLACE INTO `modx_system_settings` VALUES ('ms2_cart_handler_class','msCartHandler','textfield','minishop2','ms2_cart',NULL);
REPLACE INTO `modx_system_settings` VALUES ('ms2_cart_max_count','1000','numberfield','minishop2','ms2_cart',NULL);
REPLACE INTO `modx_system_settings` VALUES ('ms2_category_content_default','','textarea','minishop2','ms2_category',NULL);
REPLACE INTO `modx_system_settings` VALUES ('ms2_category_grid_fields','id,menuindex,pagetitle,article,price,thumb,new,favorite,popular','textarea','minishop2','ms2_category',NULL);
REPLACE INTO `modx_system_settings` VALUES ('ms2_category_id_as_alias','','combo-boolean','minishop2','ms2_category',NULL);
REPLACE INTO `modx_system_settings` VALUES ('ms2_category_remember_tabs','1','combo-boolean','minishop2','ms2_category',NULL);
REPLACE INTO `modx_system_settings` VALUES ('ms2_category_show_comments','1','combo-boolean','minishop2','ms2_category',NULL);
REPLACE INTO `modx_system_settings` VALUES ('ms2_category_show_nested_products','1','combo-boolean','minishop2','ms2_category',NULL);
REPLACE INTO `modx_system_settings` VALUES ('ms2_category_show_options','','combo-boolean','minishop2','ms2_category',NULL);
REPLACE INTO `modx_system_settings` VALUES ('ms2_chunks_categories','8','textfield','minishop2','ms2_main','2024-11-15 17:56:33');
REPLACE INTO `modx_system_settings` VALUES ('ms2_date_format','%d.%m.%y <span class=\"gray\">%H:%M</span>','textfield','minishop2','ms2_order',NULL);
REPLACE INTO `modx_system_settings` VALUES ('ms2_email_manager','','textfield','minishop2','ms2_order',NULL);
REPLACE INTO `modx_system_settings` VALUES ('ms2_frontend_css','[[+cssUrl]]web/default.css','textfield','minishop2','ms2_frontend',NULL);
REPLACE INTO `modx_system_settings` VALUES ('ms2_frontend_js','[[+jsUrl]]web/default.js','textfield','minishop2','ms2_frontend',NULL);
REPLACE INTO `modx_system_settings` VALUES ('ms2_frontend_message_css','[[+cssUrl]]web/lib/jquery.jgrowl.min.css','textfield','minishop2','ms2_frontend',NULL);
REPLACE INTO `modx_system_settings` VALUES ('ms2_frontend_message_js','[[+jsUrl]]web/lib/jquery.jgrowl.min.js','textfield','minishop2','ms2_frontend',NULL);
REPLACE INTO `modx_system_settings` VALUES ('ms2_frontend_message_js_settings','[[+jsUrl]]web/message_settings.js','textfield','minishop2','ms2_frontend',NULL);
REPLACE INTO `modx_system_settings` VALUES ('ms2_order_address_fields','receiver,phone,index,country,region,city,metro,street,building,entrance,floor,room,comment,text_address','textarea','minishop2','ms2_order',NULL);
REPLACE INTO `modx_system_settings` VALUES ('ms2_order_format_num','%y%m','textfield','minishop2','ms2_order',NULL);
REPLACE INTO `modx_system_settings` VALUES ('ms2_order_format_num_separator','/','textfield','minishop2','ms2_order',NULL);
REPLACE INTO `modx_system_settings` VALUES ('ms2_order_grid_fields','id,num,customer,status,cost,weight,delivery,payment,createdon,updatedon,comment','textarea','minishop2','ms2_order',NULL);
REPLACE INTO `modx_system_settings` VALUES ('ms2_order_handler_class','msOrderHandler','textfield','minishop2','ms2_order',NULL);
REPLACE INTO `modx_system_settings` VALUES ('ms2_order_product_fields','name,vendor_name,product_article,weight,price,count,cost','textarea','minishop2','ms2_order','2024-11-15 17:56:33');
REPLACE INTO `modx_system_settings` VALUES ('ms2_order_product_options','size,color','textarea','minishop2','ms2_order',NULL);
REPLACE INTO `modx_system_settings` VALUES ('ms2_order_user_groups','','textfield','minishop2','ms2_order',NULL);
REPLACE INTO `modx_system_settings` VALUES ('ms2_plugins','[]','textarea','minishop2','ms2_main',NULL);
REPLACE INTO `modx_system_settings` VALUES ('ms2_price_format','[2, \".\", \" \"]','textfield','minishop2','ms2_product',NULL);
REPLACE INTO `modx_system_settings` VALUES ('ms2_price_format_no_zeros','1','combo-boolean','minishop2','ms2_product',NULL);
REPLACE INTO `modx_system_settings` VALUES ('ms2_product_extra_fields','price,old_price,article,weight,color,size,vendor,made_in,tags,new,popular,favorite','textarea','minishop2','ms2_product',NULL);
REPLACE INTO `modx_system_settings` VALUES ('ms2_product_id_as_alias','','combo-boolean','minishop2','ms2_product',NULL);
REPLACE INTO `modx_system_settings` VALUES ('ms2_product_remember_tabs','1','combo-boolean','minishop2','ms2_product',NULL);
REPLACE INTO `modx_system_settings` VALUES ('ms2_product_show_comments','1','combo-boolean','minishop2','ms2_product',NULL);
REPLACE INTO `modx_system_settings` VALUES ('ms2_product_show_in_tree_default','','combo-boolean','minishop2','ms2_product',NULL);
REPLACE INTO `modx_system_settings` VALUES ('ms2_product_source_default','2','modx-combo-source','minishop2','ms2_product','2024-11-15 17:56:33');
REPLACE INTO `modx_system_settings` VALUES ('ms2_product_tab_categories','1','combo-boolean','minishop2','ms2_product',NULL);
REPLACE INTO `modx_system_settings` VALUES ('ms2_product_tab_extra','1','combo-boolean','minishop2','ms2_product',NULL);
REPLACE INTO `modx_system_settings` VALUES ('ms2_product_tab_gallery','1','combo-boolean','minishop2','ms2_product',NULL);
REPLACE INTO `modx_system_settings` VALUES ('ms2_product_tab_links','1','combo-boolean','minishop2','ms2_product',NULL);
REPLACE INTO `modx_system_settings` VALUES ('ms2_product_tab_options','1','combo-boolean','minishop2','ms2_product',NULL);
REPLACE INTO `modx_system_settings` VALUES ('ms2_product_thumbnail_default','{assets_url}components/minishop2/img/mgr/ms2_thumb.png','textfield','minishop2','ms2_product',NULL);
REPLACE INTO `modx_system_settings` VALUES ('ms2_register_frontend','1','combo-boolean','minishop2','ms2_frontend',NULL);
REPLACE INTO `modx_system_settings` VALUES ('ms2_services','{\"cart\":[],\"order\":[],\"payment\":[],\"delivery\":[]}','textarea','minishop2','ms2_main',NULL);
REPLACE INTO `modx_system_settings` VALUES ('ms2_template_category_default','','modx-combo-template','minishop2','ms2_category',NULL);
REPLACE INTO `modx_system_settings` VALUES ('ms2_template_product_default','','modx-combo-template','minishop2','ms2_product',NULL);
REPLACE INTO `modx_system_settings` VALUES ('ms2_tmp_storage','session','textfield','minishop2','ms2_main',NULL);
REPLACE INTO `modx_system_settings` VALUES ('ms2_weight_format','[3, \".\", \" \"]','textfield','minishop2','ms2_product',NULL);
REPLACE INTO `modx_system_settings` VALUES ('ms2_weight_format_no_zeros','1','combo-boolean','minishop2','ms2_product',NULL);
REPLACE INTO `modx_system_settings` VALUES ('parser_class','gitModParser','textfield','core','site','2024-11-15 17:44:04');
REPLACE INTO `modx_system_settings` VALUES ('parser_class_path','{core_path}components/gitmodx/model/gitmodx/','textfield','core','site','2024-11-15 17:44:04');
REPLACE INTO `modx_system_settings` VALUES ('parser_recurse_uncacheable','1','combo-boolean','core','system',NULL);
REPLACE INTO `modx_system_settings` VALUES ('password_generated_length','10','textfield','core','authentication',NULL);
REPLACE INTO `modx_system_settings` VALUES ('password_min_length','8','textfield','core','authentication',NULL);
REPLACE INTO `modx_system_settings` VALUES ('pdoFetch.class','pdotools.pdofetch','textfield','pdotools','pdotools_main',NULL);
REPLACE INTO `modx_system_settings` VALUES ('pdofetch_class_path','{core_path}components/pdotools/model/','textfield','pdotools','pdotools_main',NULL);
REPLACE INTO `modx_system_settings` VALUES ('pdoTools.class','pdotools.pdotools','textfield','pdotools','pdotools_main',NULL);
REPLACE INTO `modx_system_settings` VALUES ('pdotools_class_path','{core_path}components/pdotools/model/','textfield','pdotools','pdotools_main',NULL);
REPLACE INTO `modx_system_settings` VALUES ('pdotools_elements_path','{core_path}elements/','textfield','pdotools','pdotools_main',NULL);
REPLACE INTO `modx_system_settings` VALUES ('pdotools_fenom_cache','','combo-boolean','pdotools','pdotools_main',NULL);
REPLACE INTO `modx_system_settings` VALUES ('pdotools_fenom_default','1','combo-boolean','pdotools','pdotools_main',NULL);
REPLACE INTO `modx_system_settings` VALUES ('pdotools_fenom_modx','','combo-boolean','pdotools','pdotools_main',NULL);
REPLACE INTO `modx_system_settings` VALUES ('pdotools_fenom_options','','textarea','pdotools','pdotools_main',NULL);
REPLACE INTO `modx_system_settings` VALUES ('pdotools_fenom_parser','1','combo-boolean','pdotools','pdotools_main','2024-11-15 19:54:30');
REPLACE INTO `modx_system_settings` VALUES ('pdotools_fenom_php','0','combo-boolean','pdotools','pdotools_main','2024-11-15 19:54:31');
REPLACE INTO `modx_system_settings` VALUES ('pdotools_fenom_save_on_errors','','combo-boolean','pdotools','pdotools_main',NULL);
REPLACE INTO `modx_system_settings` VALUES ('phpthumb_allow_src_above_docroot','','combo-boolean','core','phpthumb',NULL);
REPLACE INTO `modx_system_settings` VALUES ('phpthumb_cache_maxage','30','textfield','core','phpthumb',NULL);
REPLACE INTO `modx_system_settings` VALUES ('phpthumb_cache_maxfiles','10000','textfield','core','phpthumb',NULL);
REPLACE INTO `modx_system_settings` VALUES ('phpthumb_cache_maxsize','100','textfield','core','phpthumb',NULL);
REPLACE INTO `modx_system_settings` VALUES ('phpthumb_cache_source_enabled','','combo-boolean','core','phpthumb',NULL);
REPLACE INTO `modx_system_settings` VALUES ('phpthumb_document_root','','textfield','core','phpthumb',NULL);
REPLACE INTO `modx_system_settings` VALUES ('phpthumb_error_bgcolor','CCCCFF','textfield','core','phpthumb',NULL);
REPLACE INTO `modx_system_settings` VALUES ('phpthumb_error_fontsize','1','textfield','core','phpthumb',NULL);
REPLACE INTO `modx_system_settings` VALUES ('phpthumb_error_textcolor','FF0000','textfield','core','phpthumb',NULL);
REPLACE INTO `modx_system_settings` VALUES ('phpthumb_far','C','textfield','core','phpthumb',NULL);
REPLACE INTO `modx_system_settings` VALUES ('phpthumb_imagemagick_path','','textfield','core','phpthumb',NULL);
REPLACE INTO `modx_system_settings` VALUES ('phpthumb_nohotlink_enabled','1','combo-boolean','core','phpthumb',NULL);
REPLACE INTO `modx_system_settings` VALUES ('phpthumb_nohotlink_erase_image','1','combo-boolean','core','phpthumb',NULL);
REPLACE INTO `modx_system_settings` VALUES ('phpthumb_nohotlink_text_message','Off-server thumbnailing is not allowed','textfield','core','phpthumb',NULL);
REPLACE INTO `modx_system_settings` VALUES ('phpthumb_nohotlink_valid_domains','{http_host}','textfield','core','phpthumb',NULL);
REPLACE INTO `modx_system_settings` VALUES ('phpthumb_nooffsitelink_enabled','','combo-boolean','core','phpthumb',NULL);
REPLACE INTO `modx_system_settings` VALUES ('phpthumb_nooffsitelink_erase_image','1','combo-boolean','core','phpthumb',NULL);
REPLACE INTO `modx_system_settings` VALUES ('phpthumb_nooffsitelink_require_refer','','combo-boolean','core','phpthumb',NULL);
REPLACE INTO `modx_system_settings` VALUES ('phpthumb_nooffsitelink_text_message','Off-server linking is not allowed','textfield','core','phpthumb',NULL);
REPLACE INTO `modx_system_settings` VALUES ('phpthumb_nooffsitelink_valid_domains','{http_host}','textfield','core','phpthumb',NULL);
REPLACE INTO `modx_system_settings` VALUES ('phpthumb_nooffsitelink_watermark_src','','textfield','core','phpthumb',NULL);
REPLACE INTO `modx_system_settings` VALUES ('phpthumb_zoomcrop','0','textfield','core','phpthumb',NULL);
REPLACE INTO `modx_system_settings` VALUES ('preserve_menuindex','1','combo-boolean','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('principal_targets','modAccessContext,modAccessResourceGroup,modAccessCategory,sources.modAccessMediaSource,modAccessNamespace','textfield','core','authentication',NULL);
REPLACE INTO `modx_system_settings` VALUES ('proxy_auth_type','BASIC','textfield','core','proxy',NULL);
REPLACE INTO `modx_system_settings` VALUES ('proxy_host','','textfield','core','proxy',NULL);
REPLACE INTO `modx_system_settings` VALUES ('proxy_password','','text-password','core','proxy',NULL);
REPLACE INTO `modx_system_settings` VALUES ('proxy_port','','textfield','core','proxy',NULL);
REPLACE INTO `modx_system_settings` VALUES ('proxy_username','','textfield','core','proxy',NULL);
REPLACE INTO `modx_system_settings` VALUES ('publish_default','','combo-boolean','core','site',NULL);
REPLACE INTO `modx_system_settings` VALUES ('rb_base_dir','','textfield','core','file',NULL);
REPLACE INTO `modx_system_settings` VALUES ('rb_base_url','','textfield','core','file',NULL);
REPLACE INTO `modx_system_settings` VALUES ('request_controller','index.php','textfield','core','gateway',NULL);
REPLACE INTO `modx_system_settings` VALUES ('request_method_strict','0','combo-boolean','core','gateway',NULL);
REPLACE INTO `modx_system_settings` VALUES ('request_param_alias','q','textfield','core','gateway',NULL);
REPLACE INTO `modx_system_settings` VALUES ('request_param_id','id','textfield','core','gateway',NULL);
REPLACE INTO `modx_system_settings` VALUES ('resolve_hostnames','0','combo-boolean','core','system',NULL);
REPLACE INTO `modx_system_settings` VALUES ('resource_static_allow_absolute','0','combo-boolean','core','static_resources',NULL);
REPLACE INTO `modx_system_settings` VALUES ('resource_static_path','{assets_path}','textfield','core','static_resources',NULL);
REPLACE INTO `modx_system_settings` VALUES ('resource_tree_node_name','pagetitle','textfield','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('resource_tree_node_name_fallback','pagetitle','textfield','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('resource_tree_node_tooltip','','textfield','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('richtext_default','1','combo-boolean','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('search_default','1','combo-boolean','core','site',NULL);
REPLACE INTO `modx_system_settings` VALUES ('send_poweredby_header','0','combo-boolean','core','system',NULL);
REPLACE INTO `modx_system_settings` VALUES ('server_offset_time','0','textfield','core','system',NULL);
REPLACE INTO `modx_system_settings` VALUES ('server_protocol','http','textfield','core','system',NULL);
REPLACE INTO `modx_system_settings` VALUES ('session_cookie_domain','','textfield','core','session',NULL);
REPLACE INTO `modx_system_settings` VALUES ('session_cookie_httponly','1','combo-boolean','core','session',NULL);
REPLACE INTO `modx_system_settings` VALUES ('session_cookie_lifetime','604800','textfield','core','session',NULL);
REPLACE INTO `modx_system_settings` VALUES ('session_cookie_path','','textfield','core','session',NULL);
REPLACE INTO `modx_system_settings` VALUES ('session_cookie_samesite','','textfield','core','session',NULL);
REPLACE INTO `modx_system_settings` VALUES ('session_cookie_secure','','combo-boolean','core','session',NULL);
REPLACE INTO `modx_system_settings` VALUES ('session_gc_maxlifetime','604800','textfield','core','session',NULL);
REPLACE INTO `modx_system_settings` VALUES ('session_handler_class','modSessionHandler','textfield','core','session',NULL);
REPLACE INTO `modx_system_settings` VALUES ('session_name','','textfield','core','session',NULL);
REPLACE INTO `modx_system_settings` VALUES ('settings_distro','traditional','textfield','core','system',NULL);
REPLACE INTO `modx_system_settings` VALUES ('settings_version','2.8.4-pl','textfield','core','system',NULL);
REPLACE INTO `modx_system_settings` VALUES ('set_header','1','combo-boolean','core','system',NULL);
REPLACE INTO `modx_system_settings` VALUES ('show_tv_categories_header','1','combo-boolean','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('signupemail_message','<p>Hello [[+uid]],</p>\n    <p>Here are your login details for the [[+sname]] MODX Manager:</p>\n\n    <p>\n        <strong>Username:</strong> [[+uid]]<br />\n        <strong>Password:</strong> [[+pwd]]<br />\n    </p>\n\n    <p>Once you log into the MODX Manager at [[+surl]], you can change your password.</p>\n\n    <p>Regards,<br />Site Administrator</p>','textarea','core','authentication',NULL);
REPLACE INTO `modx_system_settings` VALUES ('site_name','MODX GIT','textfield','core','site','2024-11-15 19:52:36');
REPLACE INTO `modx_system_settings` VALUES ('site_start','1','textfield','core','site',NULL);
REPLACE INTO `modx_system_settings` VALUES ('site_status','1','combo-boolean','core','site',NULL);
REPLACE INTO `modx_system_settings` VALUES ('site_unavailable_message','The site is currently unavailable','textfield','core','site',NULL);
REPLACE INTO `modx_system_settings` VALUES ('site_unavailable_page','0','textfield','core','site',NULL);
REPLACE INTO `modx_system_settings` VALUES ('static_elements_automate_chunks','0','combo-boolean','core','static_elements',NULL);
REPLACE INTO `modx_system_settings` VALUES ('static_elements_automate_plugins','0','combo-boolean','core','static_elements',NULL);
REPLACE INTO `modx_system_settings` VALUES ('static_elements_automate_snippets','0','combo-boolean','core','static_elements',NULL);
REPLACE INTO `modx_system_settings` VALUES ('static_elements_automate_templates','0','combo-boolean','core','static_elements',NULL);
REPLACE INTO `modx_system_settings` VALUES ('static_elements_automate_tvs','0','combo-boolean','core','static_elements',NULL);
REPLACE INTO `modx_system_settings` VALUES ('static_elements_basepath','','textfield','core','static_elements',NULL);
REPLACE INTO `modx_system_settings` VALUES ('static_elements_default_category','0','modx-combo-category','core','static_elements',NULL);
REPLACE INTO `modx_system_settings` VALUES ('static_elements_default_mediasource','0','modx-combo-source','core','static_elements',NULL);
REPLACE INTO `modx_system_settings` VALUES ('static_elements_html_extension','.tpl','textfield','core','static_elements',NULL);
REPLACE INTO `modx_system_settings` VALUES ('strip_image_paths','1','combo-boolean','core','file',NULL);
REPLACE INTO `modx_system_settings` VALUES ('symlink_merge_fields','1','combo-boolean','core','site',NULL);
REPLACE INTO `modx_system_settings` VALUES ('syncsite_default','1','combo-boolean','core','caching',NULL);
REPLACE INTO `modx_system_settings` VALUES ('tinymcerte.alignment_format','[{\"title\": \"Left\", \"icon\": \"align-left\", \"format\": \"alignleft\"},{\"title\": \"Center\", \"icon\": \"align-center\", \"format\": \"aligncenter\"},{\"title\": \"Right\", \"icon\": \"align-right\", \"format\": \"alignright\"},{\"title\": \"Justify\", \"icon\": \"align-justify\", \"format\": \"alignjustify\"}]','textarea','tinymcerte','tinymcerte.style_formats',NULL);
REPLACE INTO `modx_system_settings` VALUES ('tinymcerte.blocks_format','[{\"title\": \"Paragraph\", \"format\": \"p\"},{\"title\": \"Blockquote\", \"format\": \"blockquote\"},{\"title\": \"Div\", \"format\": \"div\"},{\"title\": \"Pre\", \"format\": \"pre\"}]','textarea','tinymcerte','tinymcerte.style_formats',NULL);
REPLACE INTO `modx_system_settings` VALUES ('tinymcerte.browser_spellcheck','','combo-boolean','tinymcerte','tinymcerte.default',NULL);
REPLACE INTO `modx_system_settings` VALUES ('tinymcerte.content_css','','textfield','tinymcerte','tinymcerte.default',NULL);
REPLACE INTO `modx_system_settings` VALUES ('tinymcerte.enable_link_list','1','combo-boolean','tinymcerte','tinymcerte.default',NULL);
REPLACE INTO `modx_system_settings` VALUES ('tinymcerte.external_config','','textfield','tinymcerte','tinymcerte.default',NULL);
REPLACE INTO `modx_system_settings` VALUES ('tinymcerte.headers_format','[{\"title\": \"Header 1\", \"format\": \"h1\"},{\"title\": \"Header 2\", \"format\": \"h2\"},{\"title\": \"Header 3\", \"format\": \"h3\"},{\"title\": \"Header 4\", \"format\": \"h4\"},{\"title\": \"Header 5\", \"format\": \"h5\"},{\"title\": \"Header 6\", \"format\": \"h6\"}]','textarea','tinymcerte','tinymcerte.style_formats',NULL);
REPLACE INTO `modx_system_settings` VALUES ('tinymcerte.image_advtab','1','combo-boolean','tinymcerte','tinymcerte.default',NULL);
REPLACE INTO `modx_system_settings` VALUES ('tinymcerte.image_class_list','','textfield','tinymcerte','tinymcerte.default',NULL);
REPLACE INTO `modx_system_settings` VALUES ('tinymcerte.inline_format','[{\"title\": \"Bold\", \"icon\": \"bold\", \"format\": \"bold\"},{\"title\": \"Italic\", \"icon\": \"italic\", \"format\": \"italic\"},{\"title\": \"Underline\", \"icon\": \"underline\", \"format\": \"underline\"},{\"title\": \"Strikethrough\", \"icon\": \"strike-through\", \"format\": \"strikethrough\"},{\"title\": \"Superscript\", \"icon\": \"superscript\", \"format\": \"superscript\"},{\"title\": \"Subscript\", \"icon\": \"subscript\", \"format\": \"subscript\"},{\"title\": \"Code\", \"icon\": \"sourcecode\", \"format\": \"code\"}]','textarea','tinymcerte','tinymcerte.style_formats',NULL);
REPLACE INTO `modx_system_settings` VALUES ('tinymcerte.links_across_contexts','','combo-boolean','tinymcerte','tinymcerte.default',NULL);
REPLACE INTO `modx_system_settings` VALUES ('tinymcerte.link_class_list','','textfield','tinymcerte','tinymcerte.default',NULL);
REPLACE INTO `modx_system_settings` VALUES ('tinymcerte.max_height','500','textfield','tinymcerte','tinymcerte.default',NULL);
REPLACE INTO `modx_system_settings` VALUES ('tinymcerte.menubar','file edit insert view format table tools','textfield','tinymcerte','tinymcerte.default',NULL);
REPLACE INTO `modx_system_settings` VALUES ('tinymcerte.object_resizing','1','textfield','tinymcerte','tinymcerte.default',NULL);
REPLACE INTO `modx_system_settings` VALUES ('tinymcerte.paste_as_text','','combo-boolean','tinymcerte','tinymcerte.default',NULL);
REPLACE INTO `modx_system_settings` VALUES ('tinymcerte.plugins','autoresize advlist autolink lists charmap print preview anchor visualblocks searchreplace code fullscreen insertdatetime media table paste modxlink modximage','textfield','tinymcerte','tinymcerte.default',NULL);
REPLACE INTO `modx_system_settings` VALUES ('tinymcerte.relative_urls','1','combo-boolean','tinymcerte','tinymcerte.default',NULL);
REPLACE INTO `modx_system_settings` VALUES ('tinymcerte.remove_script_host','1','combo-boolean','tinymcerte','tinymcerte.default',NULL);
REPLACE INTO `modx_system_settings` VALUES ('tinymcerte.settings','','textfield','tinymcerte','tinymcerte.default',NULL);
REPLACE INTO `modx_system_settings` VALUES ('tinymcerte.skin','modx','textfield','tinymcerte','tinymcerte.default',NULL);
REPLACE INTO `modx_system_settings` VALUES ('tinymcerte.statusbar','1','combo-boolean','tinymcerte','tinymcerte.default',NULL);
REPLACE INTO `modx_system_settings` VALUES ('tinymcerte.style_formats','[{\"title\": \"Headers\", \"items\": \"headers_format\"},{\"title\": \"Inline\", \"items\": \"inline_format\"},{\"title\": \"Blocks\", \"items\": \"blocks_format\"},{\"title\": \"Alignment\", \"items\": \"alignment_format\"}]','textarea','tinymcerte','tinymcerte.style_formats',NULL);
REPLACE INTO `modx_system_settings` VALUES ('tinymcerte.style_formats_merge','','combo-boolean','tinymcerte','tinymcerte.style_formats',NULL);
REPLACE INTO `modx_system_settings` VALUES ('tinymcerte.toolbar1','undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image','textfield','tinymcerte','tinymcerte.toolbar',NULL);
REPLACE INTO `modx_system_settings` VALUES ('tinymcerte.toolbar2','','textfield','tinymcerte','tinymcerte.toolbar',NULL);
REPLACE INTO `modx_system_settings` VALUES ('tinymcerte.toolbar3','','textfield','tinymcerte','tinymcerte.toolbar',NULL);
REPLACE INTO `modx_system_settings` VALUES ('tinymcerte.valid_elements','','textfield','tinymcerte','tinymcerte.default',NULL);
REPLACE INTO `modx_system_settings` VALUES ('topmenu_show_descriptions','1','combo-boolean','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('tree_default_sort','menuindex','textfield','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('tree_root_id','0','numberfield','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('tvs_below_content','0','combo-boolean','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('udperms_allowroot','','combo-boolean','core','authentication',NULL);
REPLACE INTO `modx_system_settings` VALUES ('unauthorized_page','1','textfield','core','site',NULL);
REPLACE INTO `modx_system_settings` VALUES ('upload_check_exists','1','combo-boolean','core','file',NULL);
REPLACE INTO `modx_system_settings` VALUES ('upload_files','txt,html,htm,xml,js,js.map,css,scss,less,css.map,zip,gz,rar,z,tgz,tar,mp3,mp4,aac,wav,au,wmv,avi,mpg,mpeg,pdf,doc,docx,xls,xlsx,ppt,pptx,jpg,jpeg,png,tiff,svg,svgz,gif,psd,ico,bmp,webp,odt,ods,odp,odb,odg,odf,md,ttf,woff,woff2,eot','textfield','core','file',NULL);
REPLACE INTO `modx_system_settings` VALUES ('upload_flash','swf,fla','textfield','core','file',NULL);
REPLACE INTO `modx_system_settings` VALUES ('upload_images','jpg,jpeg,png,gif,psd,ico,bmp,tiff,svg,svgz,webp','textfield','core','file',NULL);
REPLACE INTO `modx_system_settings` VALUES ('upload_maxsize','52428800','textfield','core','file','2024-11-15 16:33:05');
REPLACE INTO `modx_system_settings` VALUES ('upload_media','mp3,wav,au,wmv,avi,mpg,mpeg','textfield','core','file',NULL);
REPLACE INTO `modx_system_settings` VALUES ('user_nav_parent','usernav','textfield','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('use_alias_path','1','combo-boolean','core','furls','2024-11-15 19:41:44');
REPLACE INTO `modx_system_settings` VALUES ('use_browser','1','combo-boolean','core','file',NULL);
REPLACE INTO `modx_system_settings` VALUES ('use_context_resource_table','1','combo-boolean','core','caching',NULL);
REPLACE INTO `modx_system_settings` VALUES ('use_editor','1','combo-boolean','core','editor',NULL);
REPLACE INTO `modx_system_settings` VALUES ('use_frozen_parent_uris','1','combo-boolean','core','furls','2024-11-15 19:47:27');
REPLACE INTO `modx_system_settings` VALUES ('use_multibyte','1','combo-boolean','core','language','2024-11-15 16:33:05');
REPLACE INTO `modx_system_settings` VALUES ('use_weblink_target','','combo-boolean','core','site',NULL);
REPLACE INTO `modx_system_settings` VALUES ('webpwdreminder_message','<p>Hello [[+uid]],</p>\n\n    <p>To activate your new password click the following link:</p>\n\n    <p>[[+surl]]</p>\n\n    <p>If successful you can use the following password to login:</p>\n\n    <p><strong>Password:</strong> [[+pwd]]</p>\n\n    <p>If you did not request this email then please ignore it.</p>\n\n    <p>Regards,<br />\n    Site Administrator</p>','textarea','core','authentication',NULL);
REPLACE INTO `modx_system_settings` VALUES ('websignupemail_message','<p>Hello [[+uid]],</p>\n\n    <p>Here are your login details for [[+sname]]:</p>\n\n    <p><strong>Username:</strong> [[+uid]]<br />\n    <strong>Password:</strong> [[+pwd]]</p>\n\n    <p>Once you log into [[+sname]] at [[+surl]], you can change your password.</p>\n\n    <p>Regards,<br />\n    Site Administrator</p>','textarea','core','authentication',NULL);
REPLACE INTO `modx_system_settings` VALUES ('welcome_action','welcome','textfield','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('welcome_namespace','core','textfield','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('welcome_screen','','combo-boolean','core','manager','2024-11-15 16:33:17');
REPLACE INTO `modx_system_settings` VALUES ('welcome_screen_url','//misc.modx.com/revolution/welcome.28.html','textfield','core','manager',NULL);
REPLACE INTO `modx_system_settings` VALUES ('which_editor','TinyMCE RTE','modx-combo-rte','core','editor','2024-11-15 17:56:04');
REPLACE INTO `modx_system_settings` VALUES ('which_element_editor','CodeMirror','modx-combo-rte','core','editor','2024-11-15 17:53:04');
REPLACE INTO `modx_system_settings` VALUES ('xhtml_urls','1','combo-boolean','core','site',NULL);
/*!40000 ALTER TABLE `modx_system_settings` ENABLE KEYS */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

