
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

/*!40000 ALTER TABLE `modx_site_plugin_events` DISABLE KEYS */;
REPLACE INTO `modx_site_plugin_events` VALUES (1,'OnMODXInit',-100,0);
REPLACE INTO `modx_site_plugin_events` VALUES (1,'OnSiteRefresh',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (1,'OnWebPagePrerender',-100,0);
REPLACE INTO `modx_site_plugin_events` VALUES (3,'OnManagerPageBeforeRender',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (4,'OnHandleRequest',1,0);
REPLACE INTO `modx_site_plugin_events` VALUES (4,'OnMODXInit',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (4,'pdoToolsOnFenomInit',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (5,'OnChunkFormPrerender',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (5,'OnDocFormPrerender',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (5,'OnFileEditFormPrerender',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (5,'OnPluginFormPrerender',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (5,'OnRichTextEditorRegister',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (5,'OnSnipFormPrerender',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (5,'OnTempFormPrerender',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (6,'OnDocFormPrerender',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (6,'OnTVInputPropertiesList',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (6,'OnTVInputRenderList',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (7,'OnDocFormPrerender',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (8,'OnFileManagerUpload',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (9,'OnManagerPageBeforeRender',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (9,'OnRichTextBrowserInit',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (9,'OnRichTextEditorInit',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (9,'OnRichTextEditorRegister',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (10,'msOnChangeOrderStatus',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (10,'OnHandleRequest',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (10,'OnLoadWebDocument',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (10,'OnManagerPageBeforeRender',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (10,'OnMODXInit',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (10,'OnUserSave',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (10,'OnWebPageInit',0,0);
/*!40000 ALTER TABLE `modx_site_plugin_events` ENABLE KEYS */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

